# Generated by Django 4.0.3 on 2022-03-24 11:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('bdate', models.DateField(default=django.utils.timezone.now)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=50)),
                ('address', models.TextField(max_length=191)),
                ('usertype', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'Person',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=50)),
                ('time_slot', models.CharField(choices=[('M', 'Morning (9:00 to 12:00)'), ('A', 'Afternoon (13:00 to 17:00)'), ('E', 'Evening (18:00 to 22:00')], max_length=100)),
                ('price', models.IntegerField()),
                ('status', models.CharField(choices=[('0', 'Not available'), ('1', 'Available')], max_length=15)),
                ('roomnumber', models.IntegerField()),
            ],
            options={
                'db_table': 'Room',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('date', models.DateField()),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('reservation_id', models.CharField(default=uuid.uuid4, editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.room')),
            ],
            options={
                'db_table': 'Reservation',
            },
        ),
    ]
